/*
 *  Copyright (c) 2022 Avesha, Inc. All rights reserved.
 *
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

//This file is autogenerated, do not edit;

package schema

var (
	EventLicenseSecretNotFound = "LicenseSecretNotFound"
	EventNetPolViolation = "NetPolViolation"
	EventMachineFileNotFound = "MachineFileNotFound"
	EventMachineFileInvalid = "MachineFileInvalid"
	EventLicenseKeyInvalid = "LicenseKeyInvalid"
	EventLicenseExpired = "LicenseExpired"
	EventLicenseExpiredGracePeriodOn = "LicenseExpiredGracePeriodOn"
	EventMachineFingerPrintErr = "MachineFingerPrintErr"
	EventGotMachineFingerPrint = "GotMachineFingerPrint"
	EventConfigMapErr = "ConfigMapErr"
	EventGotConfigMap = "GotConfigMap"
	EventLicenseProxyUnreachable = "LicenseProxyUnreachable"
	EventLicenseDeployError = "LicenseDeployError"
	EventLicenseDeploySuccess = "LicenseDeploySuccess"
	EventClusterMetadataCollectionFailed = "ClusterMetadataCollectionFailed"
	EventClusterMetadataCollectionSuccess = "ClusterMetadataCollectionSuccess"
	EventLicenseDataFetchError = "LicenseDataFetchError"
	EventLicenseDataFetchSuccess = "LicenseDataFetchSuccess"
	EventLicenseSecretCreationFailed = "LicenseSecretCreationFailed"
	EventLicenseSecretCreationSuccess = "LicenseSecretCreationSuccess"
	EventProjectDeleted = "ProjectDeleted"
	EventProjectDeletionFailed = "ProjectDeletionFailed"
	EventClusterDeleted = "ClusterDeleted"
	EventClusterDeletionFailed = "ClusterDeletionFailed"
	EventSliceConfigDeleted = "SliceConfigDeleted"
	EventSliceConfigDeletionFailed = "SliceConfigDeletionFailed"
	EventServiceExportConfigDeleted = "ServiceExportConfigDeleted"
	EventServiceExportConfigDeletionFailed = "ServiceExportConfigDeletionFailed"
	EventSliceQoSConfigDeleted = "SliceQoSConfigDeleted"
	EventSliceQoSConfigDeletionFailed = "SliceQoSConfigDeletionFailed"
	EventSecretDeleted = "SecretDeleted"
	EventSecretDeletionFailed = "SecretDeletionFailed"
	EventNamespaceCreated = "NamespaceCreated"
	EventNamespaceCreationFailed = "NamespaceCreationFailed"
	EventNamespaceDeleted = "NamespaceDeleted"
	EventNamespaceDeletionFailed = "NamespaceDeletionFailed"
	EventWorkerClusterRoleCreated = "WorkerClusterRoleCreated"
	EventWorkerClusterRoleCreationFailed = "WorkerClusterRoleCreationFailed"
	EventWorkerClusterRoleUpdated = "WorkerClusterRoleUpdated"
	EventWorkerClusterRoleUpdateFailed = "WorkerClusterRoleUpdateFailed"
	EventReadOnlyRoleCreated = "ReadOnlyRoleCreated"
	EventReadOnlyRoleCreationFailed = "ReadOnlyRoleCreationFailed"
	EventReadOnlyRoleUpdated = "ReadOnlyRoleUpdated"
	EventReadOnlyRoleUpdateFailed = "ReadOnlyRoleUpdateFailed"
	EventReadWriteRoleCreated = "ReadWriteRoleCreated"
	EventReadWriteRoleCreationFailed = "ReadWriteRoleCreationFailed"
	EventReadWriteRoleUpdated = "ReadWriteRoleUpdated"
	EventReadWriteRoleUpdateFailed = "ReadWriteRoleUpdateFailed"
	EventServiceAccountCreated = "ServiceAccountCreated"
	EventServiceAccountCreationFailed = "ServiceAccountCreationFailed"
	EventServiceAccountSecretCreated = "ServiceAccountSecretCreated"
	EventServiceAccountSecretCreationFailed = "ServiceAccountSecretCreationFailed"
	EventDefaultRoleBindingCreated = "DefaultRoleBindingCreated"
	EventDefaultRoleBindingCreationFailed = "DefaultRoleBindingCreationFailed"
	EventDefaultRoleBindingUpdated = "DefaultRoleBindingUpdated"
	EventDefaultRoleBindingUpdateFailed = "DefaultRoleBindingUpdateFailed"
	EventDefaultRoleBindingDeleted = "DefaultRoleBindingDeleted"
	EventDefaultRoleBindingDeletionFailed = "DefaultRoleBindingDeletionFailed"
	EventInactiveRoleBindingDeleted = "InactiveRoleBindingDeleted"
	EventInactiveRoleBindingDeletionFailed = "InactiveRoleBindingDeletionFailed"
	EventInactiveServiceAccountDeleted = "InactiveServiceAccountDeleted"
	EventInactiveServiceAccountDeletionFailed = "InactiveServiceAccountDeletionFailed"
	EventServiceAccountDeleted = "ServiceAccountDeleted"
	EventServiceAccountDeletionFailed = "ServiceAccountDeletionFailed"
	EventDefaultDeploymentSliceRoleTemplateCreationFailed = "DefaultDeploymentSliceRoleTemplateCreationFailed"
	EventDefaultDeploymentSliceRoleTemplateCreated = "DefaultDeploymentSliceRoleTemplateCreated"
	EventDefaultReaderSliceRoleTemplateCreationFailed = "DefaultReaderSliceRoleTemplateCreationFailed"
	EventDefaultReaderSliceRoleTemplateCreated = "DefaultReaderSliceRoleTemplateCreated"
	EventSliceResourceQuotaCreationFailed = "SliceResourceQuotaCreationFailed"
	EventSliceResourceQuotaCreatedOnSliceConfigCreation = "SliceResourceQuotaCreatedOnSliceConfigCreation"
	EventSliceNodeAffinityDeletionFailed = "SliceNodeAffinityDeletionFailed"
	EventSliceNodeAffinityDeleted = "SliceNodeAffinityDeleted"
	EventSetSliceConfigAsOwnerOfSliceNodeAffinityFailed = "SetSliceConfigAsOwnerOfSliceNodeAffinityFailed"
	EventSetSliceConfigAsOwnerOfSliceNodeAffinitySucceeded = "SetSliceConfigAsOwnerOfSliceNodeAffinitySucceeded"
	EventSliceResourceQuotaDeletionFailed = "SliceResourceQuotaDeletionFailed"
	EventSliceResourceQuotaDeleted = "SliceResourceQuotaDeleted"
	EventSliceResourceQuotaRecreationFailed = "SliceResourceQuotaRecreationFailed"
	EventSliceResourceQuotaRecreated = "SliceResourceQuotaRecreated"
	EventSetSliceConfigAsOwnerOfSliceResourceQuotaFailed = "SetSliceConfigAsOwnerOfSliceResourceQuotaFailed"
	EventSetSliceConfigAsOwnerOfSliceResourceQuotaSucceeded = "SetSliceConfigAsOwnerOfSliceResourceQuotaSucceeded"
	EventSliceResourceQuotaCreated = "SliceResourceQuotaCreated"
	EventSliceResourceQuotaUpdated = "SliceResourceQuotaUpdated"
	EventAllRQSpecificationViolationMetricsResetSuccess = "AllRQSpecificationViolationMetricsResetSuccess"
	EventSliceRQSpecificationViolationMetricsResetSuccess = "SliceRQSpecificationViolationMetricsResetSuccess"
	EventClusterRQSpecificationViolationMetricsResetSuccess = "ClusterRQSpecificationViolationMetricsResetSuccess"
	EventOutdatedNamespaceRQSpecificationViolationMetricsResetSuccess = "OutdatedNamespaceRQSpecificationViolationMetricsResetSuccess"
	EventOutdatedClusterRQSpecificationViolationMetricsResetSuccess = "OutdatedClusterRQSpecificationViolationMetricsResetSuccess"
	EventSliceRoleBindingDeletingFailed = "SliceRoleBindingDeletingFailed"
	EventSliceRoleBindingDeleted = "SliceRoleBindingDeleted"
	EventSetSliceConfigAsOwnerOfSliceRoleBindingFailed = "SetSliceConfigAsOwnerOfSliceRoleBindingFailed"
	EventSetSliceConfigAsOwnerOfSliceRoleBindingSucceeded = "SetSliceConfigAsOwnerOfSliceRoleBindingSucceeded"
	EventSliceRoleTemplateDeletionFailed = "SliceRoleTemplateDeletionFailed"
	EventSliceRoleTemplateDeleted = "SliceRoleTemplateDeleted"
	EventWorkerSliceRoleBindingReconciliationSuccess = "WorkerSliceRoleBindingReconciliationSuccess"
)