/*
 *  Copyright (c) 2022 Avesha, Inc. All rights reserved.
 *
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

//This file is autogenerated, do not edit;

package schema

const (
	EventSliceDeletionFailed = "SliceDeletionFailed"
	EventNetPolViolation = "NetPolViolation"
	EventLicenseSecretNotFound = "LicenseSecretNotFound"
	EventMachineFileNotFound = "MachineFileNotFound"
	EventMachineFileInvalid = "MachineFileInvalid"
	EventLicenseKeyInvalid = "LicenseKeyInvalid"
	EventLicenseExpired = "LicenseExpired"
	EventLicenseExpiredGracePeriodOn = "LicenseExpiredGracePeriodOn"
	EventProjectDeleted = "ProjectDeleted"
	EventProjectCreated = "ProjectCreated"
	EventProjectUpdated = "ProjectUpdated"
	EventUserCreated = "UserCreated"
	EventUserRemoved = "UserRemoved"
	EventClusterDeleted = "ClusterDeleted"
	EventClusterCreated = "ClusterCreated"
	EventClusterUpdated = "ClusterUpdated"
	EventSliceConfigDeleted = "SliceConfigDeleted"
	EventSliceConfigCreated = "SliceConfigCreated"
	EventSliceConfigUpdated = "SliceConfigUpdated"
	EventServiceExportConfigDeleted = "ServiceExportConfigDeleted"
	EventServiceExportConfigCreated = "ServiceExportConfigCreated"
	EventServiceExportConfigUpdated = "ServiceExportConfigUpdated"
	EventSliceQoSConfigDeleted = "SliceQoSConfigDeleted"
	EventSliceQoSConfigCreated = "SliceQoSConfigCreated"
	EventSliceQoSConfigUpdated = "SliceQoSConfigUpdated"
)