events:
  - name: SliceDeletionFailed
    reason: SliceDeletionFailed
    action: SliceDeletion
    type: Warning
    reportingController: controller
    message: Slice deletion failed - please ask admin to check the slice configuration on the worker cluster. <link to tech doc event-list>
  - name: LicenseSecretNotFound
    reason: LicenseNotFound
    action: LicenseValidation
    type: Warning
    reportingController: controller
    message: Secret with license config not found. Please ensure to create license secret if this is airgapped cluster.
  - name: MachineFileNotFound
    reason: MachineFileNotFound
    action: FetchMachineFileFromSecret
    type: Warning
    reportingController: controller
    message: Machine File not present in license secret.Please contact kubeslice support team.
  - name: MachineFileInvalid
    reason: MachineFileInvalid
    action: VerifyMachineFile
    type: Warning
    reportingController: controller
    message: Machine File is invalid in license secret.Please contact kubeslice support team.
  - name: LicenseKeyInvalid
    reason: LicenseKeyInvalid
    action: DecryptMachineFile
    type: Warning
    reportingController: controller
    message: License Key is invalid in license secret.Please contact kubeslice support team.
  - name: LicenseExpired
    reason: LicenseExpired
    action: ValidateLicense
    type: Warning
    reportingController: controller
    message: License Expired , please contact kubeslice support team to get it renewed!
  - name: LicenseExpiredGracePeriodOn
    reason: LicenseExpiredGracePeriodOn
    action: ValidateLicense
    type: Warning
    reportingController: controller
    message: License Expired , grace period is on ,please contact kubeslice support team to get it renewed!