events:
  - name: NetPolViolation
    reason: PolicyViolation
    action: PolicyMonitoring
    type: Warning
    reportingController: worker
    message: Network policy violation - please ask admin to check the network policy configuration on the worker cluster. <link to tech doc event-list>
  - name: ClusterUnhealthy
    reason: ComponentStatusChange
    action: CheckComponents
    type: Warning
    reportingController: worker
    message: Cluster is unhealthy - Please check if all worker components are running as expected
  - name: ClusterHealthy
    reason: ComponentStatusChange
    action: None
    type: Normal
    reportingController: worker
    message: Cluster is healthy - Cluster is back to healthy state
  - name: ClusterNodeIpUpdated
    reason: ClusterNodeIpUpdated
    action: None
    type: Normal
    reportingController: worker
    message: Successfully updated cluster as change detected in cluster nodes
  - name: ClusterNodeIpUpdateFail
    reason: ClusterNodeIpUpdateFail
    action: None
    type: Warning
    reportingController: worker
    message: Failed to update node ip in cluster CR